version: '3.7'

services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - postgresql_data_container:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: Ponkorn
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data_container:/var/log/rabbitmq/log
      - rabbitmq_data_container:/var/lib/rabbitmq
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - mongodb_data_container:/data/configdb
  
volumes:
  postgresql_data_container:
  rabbitmq_data_container:
  mongodb_data_container:

